// 常量 不要修改
const LOCAL_STORAGE_KEY_HMHN = 'LOCAL_STORAGE_KEY_HMHN' // vuex 数据持久化使用
const LOCAL_STORAGE_CODE_TABLE = 'LOCAL_STORAGE_CODE_TABLE' // 码表

export { LOCAL_STORAGE_KEY_HMHN, LOCAL_STORAGE_CODE_TABLE }
